import { Product, Category, Brand } from '../../models/product.model';
import { Order, ShippingAddress, OrderItem } from '../../models/order.model';
import { User } from '../../models/user.model';
import { Setting, AuditLog } from '../../models/admin.model';
import { ShippingMethod } from '../../models/checkout.model';

// Categories
export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Engine Parts',
    slug: 'engine-parts',
    description: 'High-quality engine components including pistons, gaskets, timing belts, and more.',
    imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400',
    _count: { products: 45 },
  },
  {
    id: 'cat-2',
    name: 'Brakes',
    slug: 'brakes',
    description: 'Premium brake pads, rotors, calipers, and complete brake kits.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    _count: { products: 32 },
  },
  {
    id: 'cat-3',
    name: 'Suspension',
    slug: 'suspension',
    description: 'Shocks, struts, control arms, and suspension components.',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
    _count: { products: 28 },
  },
  {
    id: 'cat-4',
    name: 'Electrical',
    slug: 'electrical',
    description: 'Batteries, alternators, starters, and electrical components.',
    imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400',
    _count: { products: 56 },
  },
  {
    id: 'cat-5',
    name: 'Filters',
    slug: 'filters',
    description: 'Oil filters, air filters, fuel filters, and cabin filters.',
    imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400',
    _count: { products: 67 },
  },
  {
    id: 'cat-6',
    name: 'Exhaust',
    slug: 'exhaust',
    description: 'Mufflers, catalytic converters, exhaust pipes, and performance exhaust systems.',
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400',
    _count: { products: 23 },
  },
];

// Brands
export const MOCK_BRANDS: Brand[] = [
  { id: 'brand-1', name: 'Bosch', slug: 'bosch' },
  { id: 'brand-2', name: 'Denso', slug: 'denso' },
  { id: 'brand-3', name: 'ACDelco', slug: 'acdelco' },
  { id: 'brand-4', name: 'Moog', slug: 'moog' },
  { id: 'brand-5', name: 'Monroe', slug: 'monroe' },
  { id: 'brand-6', name: 'NGK', slug: 'ngk' },
  { id: 'brand-7', name: 'Brembo', slug: 'brembo' },
  { id: 'brand-8', name: 'K&N', slug: 'kn' },
  { id: 'brand-9', name: 'Bilstein', slug: 'bilstein' },
  { id: 'brand-10', name: 'Wagner', slug: 'wagner' },
];

// Products
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'BP-2024-001',
    name: 'Premium Ceramic Brake Pads - Front',
    slug: 'premium-ceramic-brake-pads-front',
    brand: { id: 'brand-7', name: 'Brembo', slug: 'brembo' },
    brandId: 'brand-7',
    description: 'High-performance ceramic brake pads designed for superior stopping power and reduced brake dust.',
    shortDescription: 'High-performance ceramic brake pads with superior stopping power.',
    price: 89.99,
    compareAtPrice: 119.99,
    stockQuantity: 45,
    lowStockThreshold: 10,
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Brakes', slug: 'brakes' },
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    isActive: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-2',
    sku: 'OF-2024-002',
    name: 'Synthetic Oil Filter',
    slug: 'synthetic-oil-filter',
    brand: { id: 'brand-1', name: 'Bosch', slug: 'bosch' },
    brandId: 'brand-1',
    description: 'Premium synthetic oil filter with advanced filtration media. Captures 99% of contaminants.',
    shortDescription: 'Premium synthetic oil filter with 99% filtration efficiency.',
    price: 12.99,
    stockQuantity: 150,
    lowStockThreshold: 30,
    categoryId: 'cat-5',
    category: { id: 'cat-5', name: 'Filters', slug: 'filters' },
    imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600',
    images: ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600'],
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'prod-3',
    sku: 'SP-2024-003',
    name: 'Iridium Spark Plugs (Set of 4)',
    slug: 'iridium-spark-plugs-set-4',
    brand: { id: 'brand-6', name: 'NGK', slug: 'ngk' },
    brandId: 'brand-6',
    description: 'High-performance iridium spark plugs for improved fuel efficiency and engine performance.',
    shortDescription: 'High-performance iridium spark plugs for better fuel efficiency.',
    price: 49.99,
    compareAtPrice: 64.99,
    stockQuantity: 80,
    lowStockThreshold: 20,
    categoryId: 'cat-4',
    category: { id: 'cat-4', name: 'Electrical', slug: 'electrical' },
    imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600',
    images: ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600'],
    isActive: true,
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: 'prod-4',
    sku: 'AF-2024-004',
    name: 'High-Flow Air Filter',
    slug: 'high-flow-air-filter',
    brand: { id: 'brand-8', name: 'K&N', slug: 'kn' },
    brandId: 'brand-8',
    description: 'Washable and reusable high-flow air filter. Increases horsepower and acceleration.',
    shortDescription: 'Washable high-flow air filter for increased performance.',
    price: 54.99,
    stockQuantity: 35,
    lowStockThreshold: 10,
    categoryId: 'cat-5',
    category: { id: 'cat-5', name: 'Filters', slug: 'filters' },
    imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600',
    images: ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600'],
    isActive: true,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
  {
    id: 'prod-5',
    sku: 'SH-2024-005',
    name: 'Performance Gas Shock Absorber',
    slug: 'performance-gas-shock-absorber',
    brand: { id: 'brand-9', name: 'Bilstein', slug: 'bilstein' },
    brandId: 'brand-9',
    description: 'Monotube gas-charged shock absorber for superior ride quality and handling.',
    shortDescription: 'Monotube gas shock for superior handling.',
    price: 149.99,
    compareAtPrice: 179.99,
    stockQuantity: 22,
    lowStockThreshold: 5,
    categoryId: 'cat-3',
    category: { id: 'cat-3', name: 'Suspension', slug: 'suspension' },
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600'],
    isActive: true,
    createdAt: '2024-01-03T10:00:00Z',
    updatedAt: '2024-01-03T10:00:00Z',
  },
  {
    id: 'prod-6',
    sku: 'AL-2024-006',
    name: 'High-Output Alternator - 200A',
    slug: 'high-output-alternator-200a',
    brand: { id: 'brand-2', name: 'Denso', slug: 'denso' },
    brandId: 'brand-2',
    description: '200-amp high-output alternator for vehicles with high electrical demands.',
    shortDescription: '200-amp alternator for high electrical demands.',
    price: 289.99,
    stockQuantity: 8,
    lowStockThreshold: 3,
    categoryId: 'cat-4',
    category: { id: 'cat-4', name: 'Electrical', slug: 'electrical' },
    imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600',
    images: ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600'],
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'prod-7',
    sku: 'TB-2024-007',
    name: 'Timing Belt Kit with Water Pump',
    slug: 'timing-belt-kit-water-pump',
    brand: { id: 'brand-3', name: 'ACDelco', slug: 'acdelco' },
    brandId: 'brand-3',
    description: 'Complete timing belt kit including belt, tensioner, idler pulleys, and water pump.',
    shortDescription: 'Complete timing belt kit with water pump.',
    price: 199.99,
    compareAtPrice: 249.99,
    stockQuantity: 15,
    lowStockThreshold: 5,
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Engine Parts', slug: 'engine-parts' },
    imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600',
    images: ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600'],
    isActive: true,
    createdAt: '2023-12-28T10:00:00Z',
    updatedAt: '2023-12-28T10:00:00Z',
  },
  {
    id: 'prod-8',
    sku: 'RT-2024-008',
    name: 'Drilled & Slotted Rotors - Pair',
    slug: 'drilled-slotted-rotors-pair',
    brand: { id: 'brand-7', name: 'Brembo', slug: 'brembo' },
    brandId: 'brand-7',
    description: 'High-performance drilled and slotted brake rotors for improved heat dissipation.',
    shortDescription: 'High-performance drilled and slotted brake rotors.',
    price: 179.99,
    stockQuantity: 18,
    lowStockThreshold: 5,
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Brakes', slug: 'brakes' },
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    isActive: true,
    createdAt: '2023-12-25T10:00:00Z',
    updatedAt: '2023-12-25T10:00:00Z',
  },
];

// Orders
const createMockOrderItems = (orderId: string): OrderItem[] => [
  {
    id: 'oi-1',
    orderId,
    productId: 'prod-1',
    sku: 'BP-2024-001',
    name: 'Premium Ceramic Brake Pads - Front',
    price: 89.99,
    quantity: 2,
    totalPrice: 179.98,
    product: {
      id: 'prod-1',
      name: 'Premium Ceramic Brake Pads - Front',
      imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
      slug: 'premium-ceramic-brake-pads-front',
    },
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'SN-2024-001234',
    userId: 'user-1',
    addressId: 'addr-1',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    items: createMockOrderItems('order-1'),
    shippingFirstName: 'John',
    shippingLastName: 'Smith',
    shippingStreet: '123 Main Street',
    shippingApartment: null,
    shippingCity: 'Detroit',
    shippingState: 'MI',
    shippingZipCode: '48201',
    shippingCountry: 'USA',
    shippingPhone: '(555) 123-4567',
    shippingMethod: 'Standard Shipping',
    shippingCarrier: null,
    trackingNumber: null,
    notes: null,
    shippingAmount: 0,
    subtotal: 359.97,
    taxAmount: 21.60,
    discountAmount: 0,
    totalAmount: 381.57,
    createdAt: '2024-01-10T14:30:00Z',
    updatedAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'order-2',
    orderNumber: 'SN-2024-001235',
    userId: 'user-1',
    addressId: 'addr-1',
    status: 'PROCESSING',
    paymentStatus: 'PAID',
    items: [{
      id: 'oi-3',
      orderId: 'order-2',
      productId: 'prod-3',
      sku: 'SP-2024-003',
      name: 'Iridium Spark Plugs (Set of 4)',
      price: 49.99,
      quantity: 1,
      totalPrice: 49.99,
      product: {
        id: 'prod-3',
        name: 'Iridium Spark Plugs (Set of 4)',
        imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600',
        slug: 'iridium-spark-plugs-set-4',
      },
    }],
    shippingFirstName: 'John',
    shippingLastName: 'Smith',
    shippingStreet: '123 Main Street',
    shippingApartment: null,
    shippingCity: 'Detroit',
    shippingState: 'MI',
    shippingZipCode: '48201',
    shippingCountry: 'USA',
    shippingPhone: '(555) 123-4567',
    shippingMethod: 'Express Shipping',
    shippingCarrier: null,
    trackingNumber: null,
    notes: null,
    shippingAmount: 12.99,
    subtotal: 49.99,
    taxAmount: 3.00,
    discountAmount: 0,
    totalAmount: 65.98,
    createdAt: '2024-01-18T10:15:00Z',
    updatedAt: '2024-01-18T10:15:00Z',
  },
  {
    id: 'order-3',
    orderNumber: 'SN-2024-001236',
    userId: 'user-2',
    addressId: 'addr-2',
    status: 'PENDING',
    paymentStatus: 'PENDING',
    items: [{
      id: 'oi-4',
      orderId: 'order-3',
      productId: 'prod-5',
      sku: 'SH-2024-005',
      name: 'Performance Gas Shock Absorber',
      price: 149.99,
      quantity: 4,
      totalPrice: 599.96,
      product: {
        id: 'prod-5',
        name: 'Performance Gas Shock Absorber',
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600',
        slug: 'performance-gas-shock-absorber',
      },
    }],
    shippingFirstName: 'Jane',
    shippingLastName: 'Doe',
    shippingStreet: '456 Oak Avenue',
    shippingApartment: null,
    shippingCity: 'Chicago',
    shippingState: 'IL',
    shippingZipCode: '60601',
    shippingCountry: 'USA',
    shippingPhone: '(555) 987-6543',
    shippingMethod: 'Standard Shipping',
    shippingCarrier: null,
    trackingNumber: null,
    notes: null,
    shippingAmount: 0,
    subtotal: 599.96,
    taxAmount: 36.00,
    discountAmount: 0,
    totalAmount: 635.96,
    createdAt: '2024-01-20T16:45:00Z',
    updatedAt: '2024-01-20T16:45:00Z',
  },
];

// Users
export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    email: 'john.smith@example.com',
    firstName: 'John',
    lastName: 'Smith',
    phone: '(555) 123-4567',
    role: 'CUSTOMER',
    createdAt: '2023-06-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    email: 'jane.doe@example.com',
    firstName: 'Jane',
    lastName: 'Doe',
    phone: '(555) 987-6543',
    role: 'CUSTOMER',
    createdAt: '2023-08-20T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'user-3',
    email: 'manager@snautoparts.com',
    firstName: 'Mike',
    lastName: 'Manager',
    role: 'MANAGER',
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'user-4',
    email: 'admin@snautoparts.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'ADMIN',
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
];

// Settings
export const MOCK_SETTINGS: Setting[] = [
  {
    id: 'setting-1',
    key: 'store_name',
    value: 'SN Auto Parts',
    category: 'general',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'setting-2',
    key: 'store_email',
    value: 'support@snautoparts.com',
    category: 'general',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'setting-3',
    key: 'free_shipping_threshold',
    value: 75,
    category: 'shipping',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'setting-4',
    key: 'tax_rate',
    value: 0.06,
    category: 'payments',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
];

// Audit Logs
export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'user-4',
    action: 'UPDATE_SETTING',
    resource: 'Setting',
    resourceId: 'free_shipping_threshold',
    oldData: { value: '50' },
    newData: { value: '75' },
    ipAddress: '127.0.0.1',
    userAgent: null,
    createdAt: '2024-01-18T14:30:00Z',
    user: { id: 'user-4', name: 'Admin User', email: 'admin@snautoparts.com' },
  },
  {
    id: 'log-2',
    userId: 'user-3',
    action: 'UPDATE_ORDER_STATUS',
    resource: 'Order',
    resourceId: 'order-1',
    oldData: null,
    newData: { status: 'DELIVERED' },
    ipAddress: '127.0.0.1',
    userAgent: null,
    createdAt: '2024-01-15T09:00:00Z',
    user: { id: 'user-3', name: 'Manager User', email: 'manager@snautoparts.com' },
  },
  {
    id: 'log-3',
    userId: 'user-4',
    action: 'CREATE_USER',
    resource: 'User',
    resourceId: 'user-3',
    oldData: null,
    newData: { role: 'MANAGER' },
    ipAddress: '127.0.0.1',
    userAgent: null,
    createdAt: '2024-01-01T10:00:00Z',
    user: { id: 'user-4', name: 'Admin User', email: 'admin@snautoparts.com' },
  },
];

// Shipping Methods
export const MOCK_SHIPPING_METHODS: ShippingMethod[] = [
  {
    id: 'standard',
    name: 'Standard Shipping',
    description: '5-7 business days',
    price: 9.99,
    freeThreshold: 50,
  },
  {
    id: 'express',
    name: 'Express Shipping',
    description: '2-3 business days',
    price: 19.99,
    freeThreshold: null,
  },
  {
    id: 'overnight',
    name: 'Overnight Shipping',
    description: 'Next business day',
    price: 29.99,
    freeThreshold: null,
  },
];

// Saved Addresses
export const MOCK_ADDRESSES: ShippingAddress[] = [
  {
    id: 'addr-1',
    firstName: 'John',
    lastName: 'Smith',
    street: '123 Main Street',
    city: 'Detroit',
    state: 'MI',
    zipCode: '48201',
    country: 'USA',
    phone: '(555) 123-4567',
    isDefault: true,
  },
  {
    id: 'addr-2',
    firstName: 'John',
    lastName: 'Smith',
    street: '789 Industrial Blvd',
    apartment: 'Suite 100',
    city: 'Detroit',
    state: 'MI',
    zipCode: '48202',
    country: 'USA',
    phone: '(555) 123-4567',
    isDefault: false,
  },
];
