export const APP_CONTENT = {
  brand: {
    name: 'SN Auto Parts',
    tagline: 'Quality Parts. Guaranteed Fitment.',
    description: 'Your trusted source for premium auto parts and accessories.',
    phone: '(555) 123-4567',
    email: 'support@snautoparts.com',
    address: '123 Auto Drive, Detroit, MI 48201',
  },
  navigation: {
    home: 'Home',
    shop: 'Shop',
    categories: 'Categories',
    brands: 'Brands',
    deals: 'Deals',
    about: 'About Us',
    contact: 'Contact',
    cart: 'Cart',
    account: 'Account',
    orders: 'Orders',
    login: 'Sign In',
    register: 'Create Account',
    logout: 'Sign Out',
    manager: 'Manager',
    admin: 'Admin',
  },
  home: {
    hero: {
      title: 'Quality Auto Parts You Can Trust',
      subtitle: 'Find the perfect parts for your vehicle with our extensive catalog of OEM and aftermarket components.',
      ctaPrimary: 'Shop Now',
      ctaSecondary: 'View Deals',
    },
    features: [
      {
        title: 'Guaranteed Fitment',
        description: 'Every part guaranteed to fit your vehicle or your money back.',
        icon: 'verified',
      },
      {
        title: 'Free Shipping',
        description: 'Free shipping on orders over $75. Fast delivery nationwide.',
        icon: 'local_shipping',
      },
      {
        title: 'Expert Support',
        description: 'Our ASE-certified experts are here to help you find the right parts.',
        icon: 'support_agent',
      },
      {
        title: 'Easy Returns',
        description: '30-day hassle-free returns on all unused parts.',
        icon: 'autorenew',
      },
    ],
    sections: {
      featuredProducts: 'Featured Products',
      topCategories: 'Shop by Category',
      topBrands: 'Top Brands',
      recentlyViewed: 'Recently Viewed',
    },
  },
  catalog: {
    filters: {
      title: 'Filters',
      category: 'Category',
      brand: 'Brand',
      price: 'Price Range',
      availability: 'Availability',
      inStock: 'In Stock Only',
      clearAll: 'Clear All',
      apply: 'Apply Filters',
    },
    sort: {
      label: 'Sort by',
      options: {
        newest: 'Newest',
        priceAsc: 'Price: Low to High',
        priceDesc: 'Price: High to Low',
        popularity: 'Most Popular',
        name: 'Name: A-Z',
      },
    },
    results: {
      showing: 'Showing',
      of: 'of',
      products: 'products',
      noResults: 'No products found matching your criteria.',
      adjustFilters: 'Try adjusting your filters or search term.',
    },
  },
  product: {
    sku: 'SKU',
    brand: 'Brand',
    price: 'Price',
    originalPrice: 'Was',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    lowStock: 'Only {{count}} left!',
    quantity: 'Quantity',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    specifications: 'Specifications',
    description: 'Description',
    reviews: 'Reviews',
    relatedProducts: 'Related Products',
    compatibility: 'Vehicle Compatibility',
  },
  cart: {
    title: 'Shopping Cart',
    empty: 'Your cart is empty',
    emptyMessage: 'Browse our products and add items to your cart.',
    continueShopping: 'Continue Shopping',
    item: 'Item',
    price: 'Price',
    quantity: 'Qty',
    total: 'Total',
    remove: 'Remove',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    tax: 'Tax',
    orderTotal: 'Order Total',
    proceedToCheckout: 'Proceed to Checkout',
    calculatedAtCheckout: 'Calculated at checkout',
  },
  checkout: {
    title: 'Checkout',
    steps: {
      address: 'Shipping Address',
      shipping: 'Shipping Method',
      payment: 'Payment',
      review: 'Review Order',
    },
    address: {
      title: 'Shipping Address',
      firstName: 'First Name',
      lastName: 'Last Name',
      company: 'Company (Optional)',
      address1: 'Address Line 1',
      address2: 'Address Line 2 (Optional)',
      city: 'City',
      state: 'State',
      postalCode: 'ZIP Code',
      country: 'Country',
      phone: 'Phone Number',
      saveAddress: 'Save this address for future orders',
      continue: 'Continue to Shipping',
    },
    shipping: {
      title: 'Select Shipping Method',
      continue: 'Continue to Payment',
    },
    payment: {
      title: 'Payment Information',
      cardNumber: 'Card Number',
      expiry: 'Expiration Date',
      cvc: 'CVC',
      billingAddress: 'Billing Address',
      sameAsShipping: 'Same as shipping address',
      continue: 'Review Order',
      securePayment: 'Your payment information is encrypted and secure.',
    },
    review: {
      title: 'Review Your Order',
      orderSummary: 'Order Summary',
      shippingAddress: 'Shipping Address',
      shippingMethod: 'Shipping Method',
      paymentMethod: 'Payment Method',
      items: 'Items',
      placeOrder: 'Place Order',
      agreeTerms: 'By placing this order, you agree to our Terms of Service and Privacy Policy.',
    },
    confirmation: {
      title: 'Order Confirmed!',
      thankYou: 'Thank you for your order',
      orderNumber: 'Order Number',
      emailSent: 'A confirmation email has been sent to',
      estimatedDelivery: 'Estimated Delivery',
      viewOrder: 'View Order Details',
      continueShopping: 'Continue Shopping',
    },
  },
  auth: {
    login: {
      title: 'Sign In',
      email: 'Email Address',
      password: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      submit: 'Sign In',
      noAccount: "Don't have an account?",
      createAccount: 'Create Account',
    },
    register: {
      title: 'Create Account',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email Address',
      phone: 'Phone Number (Optional)',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      submit: 'Create Account',
      hasAccount: 'Already have an account?',
      signIn: 'Sign In',
      passwordRequirements: 'Password must be at least 8 characters with one uppercase letter and one number.',
    },
    forgotPassword: {
      title: 'Reset Password',
      description: 'Enter your email address and we will send you instructions to reset your password.',
      email: 'Email Address',
      submit: 'Send Reset Link',
      backToLogin: 'Back to Sign In',
      successTitle: 'Check Your Email',
      successMessage: 'If an account exists with that email, you will receive password reset instructions.',
    },
    resetPassword: {
      title: 'Set New Password',
      password: 'New Password',
      confirmPassword: 'Confirm New Password',
      submit: 'Reset Password',
      success: 'Your password has been reset. You can now sign in with your new password.',
    },
  },
  account: {
    title: 'My Account',
    profile: {
      title: 'Profile',
      personalInfo: 'Personal Information',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      phone: 'Phone',
      update: 'Update Profile',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm New Password',
    },
    addresses: {
      title: 'Addresses',
      add: 'Add New Address',
      edit: 'Edit',
      delete: 'Delete',
      setDefault: 'Set as Default',
      default: 'Default',
    },
    orders: {
      title: 'Order History',
      noOrders: 'No orders yet',
      viewDetails: 'View Details',
      reorder: 'Reorder',
    },
  },
  orders: {
    title: 'Order History',
    orderNumber: 'Order #',
    date: 'Date',
    status: 'Status',
    total: 'Total',
    items: 'Items',
    viewDetails: 'View Details',
    trackOrder: 'Track Order',
    statuses: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      processing: 'Processing',
      shipped: 'Shipped',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
    },
  },
  manager: {
    dashboard: {
      title: 'Orders Dashboard',
      totalOrders: 'Total Orders',
      pendingOrders: 'Pending Orders',
      revenue: 'Revenue',
      avgOrderValue: 'Avg. Order Value',
    },
    orders: {
      title: 'Manage Orders',
      search: 'Search orders...',
      filter: 'Filter',
      export: 'Export',
      viewDetails: 'View Details',
      updateStatus: 'Update Status',
      fulfill: 'Mark as Fulfilled',
    },
    inventory: {
      title: 'Inventory',
      products: 'Products',
      adjustments: 'Adjustments',
      lowStock: 'Low Stock',
      search: 'Search products...',
      adjust: 'Adjust Stock',
      reason: 'Reason',
      quantity: 'Quantity',
    },
  },
  admin: {
    users: {
      title: 'Users & Roles',
      addUser: 'Add User',
      editUser: 'Edit User',
      role: 'Role',
      status: 'Status',
      lastLogin: 'Last Login',
      actions: 'Actions',
    },
    settings: {
      title: 'Settings',
      general: 'General',
      payments: 'Payments',
      shipping: 'Shipping',
      email: 'Email',
      save: 'Save Changes',
    },
    audit: {
      title: 'Audit Logs',
      user: 'User',
      action: 'Action',
      entity: 'Entity',
      timestamp: 'Timestamp',
      details: 'Details',
    },
  },
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    close: 'Close',
    confirm: 'Confirm',
    search: 'Search',
    noResults: 'No results found',
    viewAll: 'View All',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
  },
  footer: {
    company: {
      title: 'Company',
      about: 'About Us',
      careers: 'Careers',
      press: 'Press',
    },
    support: {
      title: 'Support',
      contact: 'Contact Us',
      faq: 'FAQ',
      shipping: 'Shipping Info',
      returns: 'Returns',
    },
    legal: {
      title: 'Legal',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      warranty: 'Warranty',
    },
    newsletter: {
      title: 'Stay Updated',
      description: 'Subscribe to get updates on new products and exclusive offers.',
      placeholder: 'Enter your email',
      subscribe: 'Subscribe',
    },
    copyright: '© 2026 SN Auto Parts. All rights reserved.',
  },
  validation: {
    required: 'This field is required',
    email: 'Please enter a valid email address',
    minLength: 'Must be at least {{min}} characters',
    maxLength: 'Must be no more than {{max}} characters',
    passwordMatch: 'Passwords do not match',
    phone: 'Please enter a valid phone number',
    postalCode: 'Please enter a valid ZIP code',
  },
} as const;

export type AppContent = typeof APP_CONTENT;

